/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '24/10/19 5:05 PM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 24/10/19 5:05 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
