/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '17/10/19 6:44 PM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 17/10/19 6:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
