/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '22/10/19 11:56 AM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 22/10/19 11:56 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
