/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '4/11/19 11:04 AM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 4/11/19 11:04 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
