/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '14/10/19 2:57 PM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 14/10/19 2:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
