/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '25/10/19 10:57 AM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 25/10/19 10:57 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
