/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '18/10/19 1:28 AM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 18/10/19 1:28 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
