/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '15/10/19 11:38 PM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 15/10/19 11:38 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
