SELECT * FROM EMP ORDER BY SAL;
SELECT LOWER(ENAME) FROM EMP;
SELECT * FROM EMP WHERE DEPTNO=10;
SELECT * FROM EMP WHERE DEPTNO=10 OR DEPTNO=20;
SELECT * FROM EMP WHERE SAL BETWEEN 2000 AND 5000;
SELECT * FROM EMP WHERE COMM IS NULL;
SELECT * FROM EMP WHERE JOB="CLERK";
SELECT DISTINCT DEPTNO FROM EMP;
SELECT ENAME, SAL, (IF(ISNULL(COMM)=TRUE,0,COMM) + (SAL*12)) AS ANNUAL_SAL FROM EMP;

SELECT * FROM EMP WHERE SAL=(SELECT SAL FROM EMP WHERE ENAME="SCOTT");
SELECT * FROM EMP WHERE MGR=(SELECT EMPNO FROM EMP WHERE ENAME="KING");
SELECT DISTINCT * FROM EMP ORDER BY SAL DESC LIMIT 3; 

SELECT COUNT(EMPNO),DEPTNO FROM EMP GROUP BY DEPTNO;
SELECT COUNT(EMPNO),JOB FROM EMP GROUP BY JOB;

SELECT EMP.ENAME, DEPT.DNAME FROM DEPT INNER JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO
SELECT a.ENAME, b.ENAME AS BOSS FROM EMP a INNER JOIN EMP b ON a.MGR = b.EMPNO;
SELECT DEPT.DNAME, EMP.ENAME FROM DEPT LEFT JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO;

SELECT DEPT.DNAME, EMP.ENAME 
FROM DEPT 
LEFT JOIN EMP ON DEPT.DEPTNO = EMP.DEPTNO 
WHERE EMP.ENAME IS NULL;

SELECT a.ENAME, b.ENAME AS BOSS 
FROM EMP a 
LEFT JOIN EMP b ON a.MGR = b.EMPNO;

SELECT DEPT.DNAME, COUNT(EMP.EMPNO)
FROM DEPT
LEFT JOIN EMP ON DEPT.DEPTNO=EMP.DEPTNO 
GROUP BY DEPT.DNAME;

SELECT DEPT.DNAME, COUNT(EMP.EMPNO)
FROM DEPT
LEFT JOIN EMP ON DEPT.DEPTNO=EMP.DEPTNO 
GROUP BY DEPT.DNAME 
HAVING COUNT(EMP.EMPNO) > 3;

SELECT a.ENAME, DEPT.DNAME, b.ENAME AS BOSS
FROM (EMP a 
LEFT JOIN EMP b ON a.MGR = b.EMPNO)
INNER JOIN DEPT ON a.DEPTNO = DEPT.DEPTNO;

