/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Akash Gupta' at '26/10/19 3:52 PM' with Gradle 3.0
 *
 * @author Akash Gupta, @date 26/10/19 3:52 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
